<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAot>true</PublishAot>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
	<_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>
	<Platforms>AnyCPU;x64</Platforms>
	<AssemblyName>Client</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
	<RdXmlFile Include="rd.xml" />
  </ItemGroup>
	    
  <ItemGroup>
    <PackageReference Include="ClickableTransparentOverlay" Version="9.3.0" />
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
    <PackageReference Include="DNNE" Version="2.0.8" />
    <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
    <PackageReference Include="WinFormsComInterop" Version="0.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Remove="clicksound.wav" />
    <None Remove="Properties\n8ow9e.dll" />
    <None Remove="Properties\qm0lnv.dll" />
    <None Remove="varsity_regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="clicksound.wav" />
    <EmbeddedResource Include="Properties\n8ow9e.dll" />
    <EmbeddedResource Include="Properties\qm0lnv.dll" />
    <EmbeddedResource Include="varsity_regular.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Helper">
      <HintPath>..\..\..\..\..\..\sab kuch\sab kuch\Helper.dll</HintPath>
    </Reference>
    <Reference Include="Memory">
      <HintPath>..\..\..\..\..\..\sab kuch\sab kuch\Memory.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>